/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include<stdint.h>
#include<stdio.h>

void delay(void)
{
   for(uint32_t i=0 ; i < 300000 ; i++);
}

int main(void)
{
    //peripheral register addresses
	uint32_t volatile *const pGPIODModeReg = (uint32_t*)(0x40020C00);
	uint32_t volatile *const pInPutDataReg = (uint32_t*)(0x40020C00+0x10);
	uint32_t volatile *const pOutPutDataReg = (uint32_t*)(0x40020C00+0x14);
	uint32_t volatile *const pClockCtrlReg = (uint32_t*)(0x40023800+0x30);
	uint32_t volatile *const pPullupDownReg = (uint32_t*)(0x40020C00+0x0C);

	//1.Enable the peripheral clock of GPIO peripheral
	*pClockCtrlReg |= (1 << 3);

	//2.Configure PD0,PD1,PD2,PD3 as output (rows)
	*pGPIODModeReg &= ~(0xFF); //clear
	*pGPIODModeReg |= ~ 0x55; //set

	//3.configure PD8,PD9,PD10,PD11 as input(columns)
	*pGPIODModeReg &= ~(0xFF << 16);

	//4.Enable internal pull-up registers for PD8,PD9,PD10,PD11
	*pPullupDownReg &= ~(0xFF << 16);
	*pPullupDownReg |= (0x55 << 16);

while(1)
{
	//make all rows HIGH
	*pOutPutDataReg |= 0x0f;

	//make R1 Low(PD0)
	*pOutPutDataReg &= ~( 1 << 0);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("1\n");
	}

	//check C2(PD9) low or high
	if(!(*pInPutDataReg & (1 << 9))){
		//key is pressed
		printf("2\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 10))){
		//key is pressed
		printf("3\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 11))){
		//key is pressed
		printf("A\n");
	}

	//make all rows HIGH
		*pOutPutDataReg |= 0x0f;
	//make R2 Low(PD1)
		*pOutPutDataReg &= ~( 1 << 1);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("4\n");
	}

	//check C2(PD9) low or high
	if(!(*pInPutDataReg & (1 << 9))){
		//key is pressed
		printf("5\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 10))){
		//key is pressed
		printf("6\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 11))){
		//key is pressed
		printf("B\n");
	}

	//make all rows HIGH
		*pOutPutDataReg |= 0x0f;
	//make R3 Low(PD2)
		*pOutPutDataReg &= ~( 1 << 2);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("7\n");
	}

	//check C2(PD9) low or high
	if(!(*pInPutDataReg & (1 << 9))){
		//key is pressed
		printf("8\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 10))){
		//key is pressed
		printf("9\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 11))){
		//key is pressed
		printf("C\n");
	}

	//make all rows HIGH
		*pOutPutDataReg |= 0x0f;
	//make R4 Low(PD2)
		*pOutPutDataReg &= ~( 1 << 3);

	//scan the columns
	//check C1(PD8) low or high
	if(!(*pInPutDataReg & (1 << 8))){
		//key is pressed
		delay();
		printf("*\n");
	}

	//check C2(PD9) low or high
	if(!(*pInPutDataReg & (1 << 9))){
		//key is pressed
		printf("0\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 10))){
		//key is pressed
		printf("#\n");
	}

	//check C3(PD10) low or high
	if(!(*pInPutDataReg & (1 << 11))){
		//key is pressed
		printf("D\n");
	}

}

}
